#~~~~USER INPUTS: These Global Variables Must be Changed To Fit Your .H5ad Data File~~~~~~~~~~~~~~~~~~~~~~~~~~~

# INPUT 1: UserInput_CellTypeColumn
# DESCRIPTION: Column in adata.obs that contains the meta-data that you will pseudobulk using. Eg If you have cell type information in a column called                                      cell_type put in the column name. Put in cell_type. Input must be string."

<<<<<<< HEAD
UserInput_CellTypeColumn: "cell_ontology_class"
=======
UserInput_CellTypeColumn: "compartment"
>>>>>>> 3c1fb065b25c7ca5703de1a68e8cd379c6c7289b

path: "../../../../pipeline42/datasets/TabulaSapiens"