# environment.yml

name: diff_exp  # specify your environment name
channels:
  - defaults
  - conda-forge
  - bioconda
  - anaconda

dependencies:
  - python=3.8  # specify your Python version
  - numpy
  - pandas
  - scikit-learn
  - anndata
  - scanpy
  # Conda packages can be specified with version numbers
  - matplotlib=3.1.3
  - tensorflow
  - tensorflow-probability
  - ipykernel

  # You can also use the pip section to install additional packages
  - pip:
    - batchglm
    - diffxpy

